### ISSUE TITLE
Running samples purely locally

### ISSUE THREAD

**Issue by naasking** [GoogleCloudPlatform/getting-started-dotnet#107]
I've forked this project and managed to run the first sample projects 1-hello-world and 2-structured-data against the datastore emulator after updating to the latest dlls. 3-binary-data fails no matter what I do.

First the Datastore.Create fails because the API is too old for the current emulator, so I upgrade the Google.Cloud.Datastore.V1 package just like I had to do with the others. Then I get a new error on `StorageClient.Create()`:

```
System.TypeLoadException was unhandled by user code
  HResult=-2146233054
  Message=Could not load type 'Google.Api.Gax.ScopedCredentialProvider' from assembly 'Google.Api.Gax, Version=2.2.1.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47'.
  Source=Google.Cloud.Storage.V1
  TypeName=Google.Api.Gax.ScopedCredentialProvider
  StackTrace:
       at Google.Cloud.Storage.V1.StorageClient.Create(GoogleCredential credential, EncryptionKey encryptionKey)
       at GoogleCloudSamples.Services.ImageUploader..ctor(String bucketName) in C:\Users\naask\source\repos\getting-started-dotnet\aspnet\3-binary-data\Services\ImageUploader.cs:line 31
       at GoogleCloudSamples.UnityConfig.RegisterTypes(IUnityContainer container) in C:\Users\naask\source\repos\getting-started-dotnet\aspnet\3-binary-data\App_Start\UnityConfig.cs:line 123
       at GoogleCloudSamples.UnityConfig.<>c.<.cctor>b__8_0() in C:\Users\naask\source\repos\getting-started-dotnet\aspnet\3-binary-data\App_Start\UnityConfig.cs:line 53
       at System.Lazy`1.CreateValue()
  InnerException: 
```
If I update Google.Api.Gax package, v2.5.0 replaces v2.2.1 but I still receive the same error. Am I missing some configuration step, or will these samples simply not support running purely locally?

**Comment by engelke** [comment]
This tutorial has been rewritten to use Cloud Run instead of App Engine; this issue is obsolete.
